---
version: '3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./docker/app
    image: laradast:latest
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - ${APP_PORT}:80
    networks:
      - laravel

  mariadb:
    image: mariadb:latest
    container_name: laravel_db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_USERNAME}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./docker/mariadb:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_cache
    volumes:
      - ./docker/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: laravel_mail
    ports:
      - ${MAIL_PORT}:1025
      - ${MAIL_WEB_PORT}:8025
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
